CREATE TABLE metrocleaners_appointments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer INTEGER REFERENCES metrocleaners_customers(id) ON DELETE SET NULL,
    due_date DATE NOT NULL,
    order_picked_up BOOLEAN DEFAULT false NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    date_modified TIMESTAMP
);
